theme: jekyll-theme-cayman
title: CASHNET Architecture Documentation
description: Complete payment processing system documentation with interactive diagrams

# Markdown configuration for GitHub Pages
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Enable GitHub-flavored markdown
github_flavored_markdown: true

# Plugins (GitHub Pages safe)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
