theme: jekyll-theme-cayman
title: Cashnet Architecture Docs
description: High-level system design and transaction flows

# Optional: add navigation links
header_pages:
  - index.md
  - flow.md
  - components.md
  - endtoend.md
